modules/admin/controllers/BannerController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Banner;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use vova07\fileapi\actions\UploadAction as FileAPIUpload;

class BannerController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ]
            ],
        ];
    }

    public function actions()
    {
        return [
            'fileapi-upload' => [
                'class' => FileAPIUpload::className(),
                'path' => '@webroot/uploads/temp'
            ],
            'sorting' => [
                'class' => \kotchuprik\sortable\actions\Sorting::className(),
                'query' => \app\models\Banner::find(),
            ],
        ];
    }

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Banner::find()
            ->orderBy([
              'order' => SORT_ASC
            ]),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreate()
    {
        $model = new Banner();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['index']);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = Banner::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

modules/admin/controllers/DefaultController.php
<?php

namespace app\modules\admin\controllers;

use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use yii\web\ErrorAction;

/**
 * Default controller for the `admin` module
 */
class DefaultController extends Controller
{
    /**
     * Renders the index view for the module
     *
     * @return string
     */

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => ErrorAction::class,
            ],
        ];
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->redirect(['banner/index']);
        }

        $this->layout = 'auth';

        $model = new LoginForm();
        if ($model->load(\Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['banner/index']);
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        \Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionAbout()
    {
        return $this->render('about');
    }
}

modules/admin/controllers/StatController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Viewer;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;

class StatController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ]
            ],
        ];
    }

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Viewer::findBySql("SELECT  DATE(createdAt) as createdAt, COUNT(concat(client,ipAddress)) as client, bannerId, SUM(countView) as countView, SUM(countClick) as countClick FROM viewer GROUP BY DATE(createdAt), bannerId ORDER BY createdAt DESC"),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

}

modules/admin/controllers/ViewerController.php
<?php

namespace app\modules\admin\controllers;

use Yii;
use app\models\Viewer;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
// use yii\web\NotFoundHttpException;
// use yii\filters\VerbFilter;
// use vova07\fileapi\actions\UploadAction as FileAPIUpload;

class ViewerController extends \yii\web\Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ]
            ],
        ];
    }

    // public function actions()
    // {
    //     return [
    //         'fileapi-upload' => [
    //             'class' => FileAPIUpload::className(),
    //             'path' => '@webroot/uploads/temp'
    //         ],
    //     ];
    // }

    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Viewer::find()
            ->orderBy([
              'createdAt' => SORT_DESC
            ]),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = Viewer::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

modules/admin/views/banner/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use vova07\fileapi\Widget as FileAPI;

/* @var $this yii\web\View */
/* @var $model app\models\Type */
/* @var $form yii\widgets\ActiveForm */

$options = [
    'template' => '{label}<div class="col-sm-10">{input}{error}</div>',
    'labelOptions' => ['class' => 'col-sm-2 control-label']
];
$behavior = $model->getBehavior('uploadBehavior');
?>

<div class="col-md-8 col-md-offset-2">
    <?php $form = ActiveForm::begin([
        'options' => ['class' => 'form-horizontal'],
    ]); ?>


    <?= $form->field($model, 'value', $options)
          ->widget(conquer\codemirror\CodemirrorWidget::className(), [
              'preset' => 'php',
              'options' => [
                  'rows' => 4,
              ],
          ])
           ?>

    <?= $form->field($model, 'urlLink', $options)->textInput() ?>

    <?= $form->field($model, 'urlImage', $options)->widget(
        FileAPI::className(),
        [
            'settings' => [
                'url' => ['fileapi-upload'],
                'lang' => 'ru',
            ],
            'preview' => false,
        ]
    ); ?>

    <p class="text-center">
        <img style="max-width: 130px;" src="<?= $behavior->urlAttribute('urlImage') ?>">
    </p>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Изменить', ['class' => 'btn-info md-raised md-primary btn-w-md md-button md-ink-ripple']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/admin/views/banner/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Type */

$this->title = 'Создание баннера';
$this->params['breadcrumbs'][] = ['label' => 'Banners', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<h2 class="section-header"><?= Html::encode($this->title) ?></h2>

<div class="panel panel-default">
    <div class="panel-body padding-xl">
        <div class="row">
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
    </div>
</div>

modules/admin/views/banner/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Баннеры';
$this->params['breadcrumbs'][] = $this->title;
?>

<h2 class="section-header"><?= Html::encode($this->title) ?> <?= Html::a('<span class="fa fa-plus"></span> Добавить', ['create'], ['class' => 'btn btn-info btn-xs ui-wave']) ?></h2>

<div class="panel panel-default panel-minimal">
    <div class="panel-body">
        <div class="row">
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'layout' => '{items}{pager}',
                'rowOptions' => function ($model, $key, $index, $grid) {
                    return ['data-sortable-id' => $model->id];
                },
                'columns' => [
                    [
                        'class' => \kotchuprik\sortable\grid\Column::className(),
                    ],
                    'id',
                    [
                      'attribute' => 'value',
                      'contentOptions' =>['style'=>'word-break: break-all;'],
                    ],
                    [
                        'label' => 'Изображение',
                        'format' => 'raw',
                        'value' => function ($data) {
                            if (!$data->urlImage) {
                                return '';
                            }

                            return Html::img('/uploads/banners/' . $data->urlImage, [
                                'style' => 'max-width:100px',
                            ]);
                        },
                    ],
                    [
                      'attribute' => 'urlLink',
                      'contentOptions' =>['style'=>'word-break: break-all;'],
                      'content'=>function($data){
                          return Html::a($data->urlLink,$data->urlLink,['target'=>'_blank']);
                      }
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'header' => 'Действия',
                        'headerOptions' => ['width' => '80'],
                        'buttonOptions' => ['class' => 'btn btn-link'],
                        'template' => '{update}  {delete}',
                    ],
                ],
                'options' => [
                    'data' => [
                        'sortable-widget' => 1,
                        'sortable-url' => \yii\helpers\Url::toRoute(['sorting']),
                    ]
                ],
                'tableOptions' => ['class' => 'table no-margin'],
            ]); ?>
        </div>
    </div>
</div>

modules/admin/views/banner/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\TYpe */

$this->title = 'Изменение баннера №: ' . $model->id;
?>

<h1><?= Html::encode($this->title) ?></h1>

<div class="panel panel-default">
    <div class="panel-body padding-xl">
        <div class="row">
            <?= $this->render('_form', [
                'model' => $model,
            ]) ?>
        </div>
    </div>
</div>

modules/admin/views/default/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
?>
  <div class="login-logo">
    <span><b>Admin</b>BANNER</span>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
  <p class="login-box-msg">Sign in to start your session</p>
  <?php $form = ActiveForm::begin([
      'id' => 'login-form',
      'options' => ['class' => ''],
  ]); ?>

      <?= $form->field($model, 'username', ['template' => '<div class="form-group has-feedback">{input}<span class="glyphicon glyphicon-envelope form-control-feedback"></span></div>'])
          ->textInput(['placeholder' => $model->getAttributeLabel('username'), 'options' => ['class' => 'form-control'],]) ?>

      <?= $form->field($model, 'password', ['template' => '<div class="form-group has-feedback">{input}<span class="glyphicon glyphicon-lock form-control-feedback"></span></div>'])
          ->passwordInput(['placeholder' => $model->getAttributeLabel('password'), 'options' => ['class' => 'form-control'],]) ?>
    <div class="row">
      <div class="col-xs-8">
        <div class="checkbox icheck">

        </div>
      </div>
      <!-- /.col -->
      <div class="col-xs-4">
        <?= Html::submitButton('ВОЙТИ', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
      </div>
      <!-- /.col -->
    </div>
  <?php ActiveForm::end(); ?>
</div>
<!-- /.login-box-body -->

modules/admin/views/layouts/auth.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;

$this->registerAssetBundle(\app\assets\AdminAsset::className());
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="hold-transition login-page">
<?php $this->beginBody() ?>

<div class="login-box">
        <?= $content ?>
</div>
<!-- /.login-box -->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

modules/admin/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\helpers\Url;

$this->registerAssetBundle(\app\assets\AdminAsset::className());
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="hold-transition skin-blue fixed sidebar-mini">
<?php $this->beginBody() ?>
<!-- Site wrapper -->
<div class="wrapper">
  <header class="main-header">
      <!-- Logo -->
      <a href="" class="logo">
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Admin</b>BANNER</span>
      </a>
      <!-- Header Navbar: style can be found in header.less -->
      <nav class="navbar navbar-static-top">

      </nav>
    </header>
    <!-- Left side column. contains the sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        <li>
          <a href="<?= Url::toRoute('banner/index'); ?>">
            <i class="fa fa-th"></i> <span>Banners</span>
          </a>
        </li>
        <li>
          <a href="<?= Url::toRoute('viewer/index'); ?>">
            <i class="fa fa-table"></i> <span>Views</span>
          </a>
        </li>
        <li>
          <a href="<?= Url::toRoute('stat/index'); ?>">
            <i class="fa fa-pie-chart"></i> <span>Statistic</span>
          </a>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <?= $content ?>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 0.0.1a
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="http://www.oat.ru">BPOU Omaviat</a>.</strong> All rights
    reserved.
  </footer>
</div>
<!-- ./wrapper -->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

modules/admin/views/stat/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Статистика баннеров';
$this->params['breadcrumbs'][] = $this->title;
?>

<h2 class="section-header"><?= Html::encode($this->title) ?> </h2>

<div class="panel panel-default panel-minimal">
    <div class="panel-body">
        <div class="row">
          <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'layout' => '{items}{pager}',
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    'createdAt',
                    'bannerId',
                    'countView',
                    [
                        'attribute'=>'client',
                        'label'=>'Уникальных (агент/ip-адрес)',
                    ],
                    [
                      'attribute' => 'countClick',
                      'value' => function ($data) {
                        if (!$data->countClick) {
                            return 0;
                        } else {
                            return $data->countClick;
                        }
                      },
                    ],
                ],
                'tableOptions' => ['class' => 'table no-margin'],
            ]); ?>
        </div>
    </div>
</div>

modules/admin/views/viewer/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Просмотры баннеров';
$this->params['breadcrumbs'][] = $this->title;
?>

<h2 class="section-header"><?= Html::encode($this->title) ?> </h2>

<div class="panel panel-default panel-minimal">
    <div class="panel-body">
        <div class="row">
          <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'layout' => '{items}{pager}',
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    'client',
                    'ipAddress',
                    'bannerId',
                    'countView',
                    [
                      'attribute' => 'countClick',
                      'value' => function ($data) {
                        if (!$data->countClick) {
                            return 0;
                        } else {
                            return $data->countClick;
                        }
                      },
                    ],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'header' => 'Действия',
                        'headerOptions' => ['width' => '80'],
                        'template' => '{delete}',
                    ],
                ],
                'tableOptions' => ['class' => 'table no-margin'],
            ]); ?>
        </div>
    </div>
</div>